### PR TITLE
Fix some undefined behavior and check preconditions of `unsafe` code

### LINKED ISSUE #9: Use cargo fmt
How do you feel about using `cargo fmt` for formatting the repo? I had to fight my setup not to automatically format the code 😉

### LINKED ISSUE #15: SecBox::zero_out is unsound
Sample code:
```
use secstr::SecBox;
fn main() {
    let mut mybox: SecBox<fn()> = SecBox::new(Box::new(|| println!("hi")));
    mybox.zero_out();
    mybox.unsecure()();
}
```

The `Copy` bound is not sufficient to make it legal to zero out a value of type `T`. Either the bound should be tighter, or `SecBox` should store a `MaybeUninit<T>` (and `zero_out` should be unsafe).

### LINKED ISSUE #17: Safety documentation
I've developed [a crate](https://github.com/aticu/pre) for my bachelor's thesis to make working with unsafe code a little bit safer.
It works by annotating unsafe functions with the preconditions that need to be upheld for their safety.
A call to an annotated function will fail to compile, unless it is assured at the call site that the preconditions hold.
Assuring this uses another attribute at the call site.

This has two main advantages:

- It is documented in the code why a piece of `unsafe` code is safe.
- This documentation is partially checked by the compiler. If the conditions that need to be upheld change, it can be noticed right away.

I think that secstr could benefit from such safety annotations.
If you're interested, I'd be happy to prepare a pull request to add them (as a dev-dependency).
While doing so, I'd also be going over all `unsafe` code in secstr to find out whether its usage is safe.

If you're not interested, I'd appreciate it, if you could briefly let me know why, as that would be valuable feedback for my thesis.

### LINKED ISSUE #20: The `PartialEq` implementations of `SecVec<T>` and `SecBox<T>` are UB (and wrong) in some cases
They all use the `mem::cmp` function, which is (since #18) `unsafe`, because `T` cannot have any padding bytes. If `T` does happen to have padding bytes, the comparison may succeed or it may fail (depending on the equality of the padding bytes).

See the following code for an example ([Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=21463b7ae53cf669d70ade7bc9335ab6)):

```rust
#[derive(Clone, Copy, PartialEq, Eq)]
struct X(u32, u8);

fn main() {
    let x = [X(0x987ab, 0x3f), X(0x243fe87, 0x10)];
    let y = [X(0x987ab, 0x3f), X(0x243fe87, 0x10)];

    if cmp(&x, &y) {
        println!("bytewise: ==");
    } else {
        println!("bytewise: !=");
    }
    
    if x == y {
        println!("derived:  ==");
    } else {
        println!("derived:  !=")
    }
}
```

On the playground this outputs (using a stable `--release` build):

```text
bytewise: !=
derived:  ==
```

`SecUtf8` is not affected, because it just wraps a `SecVec<u8>` and `u8` does not have any padding bytes.

I'm not sure there really is a good way to fix this.

- One option would be to make all ways of constructing these types `unsafe` and mention in the "Safety" section that `T` must not have padding bytes. That would be a pretty pervasive change though and it would require to remove the `From` implementations, because those cannot be `unsafe`. This is pretty much a non-starter.
- Use some kind of `unsafe trait NoPaddingBytes` and add a bound of `T: NoPaddingBytes`. After a (not very thorough) search I could not find anything like that on crates.io, but it shouldn't be too hard to add something like that and implement it for primitive types (and it should even be possible to make it derivable, if I'm not mistaken).

### PR DESCRIPTION
**Pull request by aticu**
Sorry it took so long, I had some unexpected complications while working on this.

closes #9
closes #15
closes #17
closes #20

Notable changes in this pull request:
- pre is now used to check and document usage of `unsafe` code (except for FFI).
- Some functions now work with raw pointers to avoid UB when a possibly invalid value is behind a reference.
- `mem::mlock`/`mem::munlock` now need mutable arguments, because `libc::madvice` uses a `*mut libc::c_void` pointer and changing from `*const` to `*mut` and using that pointer is undefined behavior.
- `SecVec::zero_out` now sets the length to `0` (this avoids making it `unsafe` like `zero_out_secbox`, which has no equivalent).

  This is technically a breaking change, however making the function `unsafe` would be too and the values in the `SecVec` would not be very interesting after a call to `zero_out_secbox` anyway.

  If you prefer to rather make it `unsafe` instead though, feel free to let me know and I'll change it.
- `SecBox::zero_out` is removed in favor of the `unsafe` function `zero_out_secbox`. Unfortunately due to an implementation detail in pre, it is not possible to add preconditions to methods (at least on stable), so I made it a freestanding function.
  
  If you'd rather have it be a method of `SecBox`, feel free to let me know and I'll change it to be that and remove the precondition from it.
- Documented the undefined behavior described in #20.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1,4 +1,7 @@
 //! A data type suitable for storing sensitive information such as passwords and private keys in memory, featuring constant time equality, mlock and zeroing out.
+extern crate core; // Needed by pre
+#[cfg(any(test, feature = "pre"))]
+extern crate pre;
```
Comment (valpackett) [inline src/lib.rs]: maybe it's time to migrate to 2018 edition..

File: src/lib.rs [hunk 2]
```diff
@@ -84,18 +118,55 @@ mod mem {
...
         }
     }
 
     #[inline(never)]
-    pub fn cmp<T: Sized + Copy>(us: &[T], them: &[T]) -> bool {
+    #[cfg_attr(
+        any(test, feature = "pre"),
+        pre::pre("`T` does not have any padding bytes")
+    )]
+    pub unsafe fn cmp<T: Sized + Copy>(us: &[T], them: &[T]) -> bool {
```
Comment (valpackett) [inline src/lib.rs]: If `zero` is working on `u8` now, why not make this `u8` too? Actually this was really silly, taking any `&[T]` to use as `&[u8]` results in code bloat (monomorphizing into the exact same thing for all used `T`) :D

File: src/lib.rs (hunk 1 above)
Comment (aticu) [reply src/lib.rs]: Do you want my to do that in this PR? It shouldn't be too much work.

Comment (valpackett) [reply src/lib.rs]: Yes, that's why I mentioned it :)

File: src/lib.rs (hunk 2 above)
Comment (aticu) [reply src/lib.rs]: The problem with that is that `&[u8]` may be UB in case `T` has padding bytes. Ideally `*const [T]` is best suited for that kind of thing, but usage of that is not really stabilized. If at least the `cmp` function should be UB-free (to have UB in less places), it should take `us: *const u8, us_len: usize, them: *const u8, then_len: usize` as arguments. I can make that change though.

Comment (valpackett) [reply src/lib.rs]: I didn't mean actually using `&[u8]`, I meant that the `T` inside is basically only used as bytes! Of course the signature should take raw pointers, just like `fn zero`.

**Comment by aticu** [comment]
I changed the things you mentioned. I don't have time for a better solution for #20 right now, but I think the current solution should fix most problems and is forward compatible with using a better implementation of the trait in the future.

I also took the liberty of running `rustfmt`, but I can remove that commit, if you don't want it.

**Comment by valpackett** [comment]
Awesome, thanks.

I guess I should release this as 1.0… if you plan on doing anything else here, please tell me :)

**Comment by aticu** [comment]
Eventually I think that a proper `NoPaddingBytes` type might benefit others too and then I guess this one could be updated to use the new one, but since this one should be forward compatible, that isn't a blocker. I guess I should make a quick PR documenting that you currently cannot implement it yourself. Other than that go ahead.

Thank you for being open to trying out pre. Would you mind giving me a quick feedback and tell me what you think about it, now that it is integrated into the code base?

**Comment by valpackett** [comment]
hm.. well I haven't actually *used* `pre`, just briefly looked at the code you changed here.

I like the idea of making developers manually write out why preconditions are satisfied, I don't think anything other than the compiler absolutely requiring this would make me think carefully about everything :D

It would be nice if the same preconditions could be also used for auto-generating runtime checks ([like in D](https://dlang.org/spec/contracts.html)), for deductive verification (like [Frama-C WP](https://allan-blanchard.fr/publis/frama-c-wp-tutorial-en.pdf) / Ada SPARK), and so on. Really I guess Rust needs to eventually get native contract syntax like in D that would be usable by all the tools including `pre` (and it should be informed by `pre`'s use case).

**Comment by aticu** [comment]
Thanks for the feedback! You may not have used pre yourself, but any feedback is valuable. Do you mind if I quote you on that for my thesis?

> Really I guess Rust needs to eventually get native contract syntax like in D that would be usable by all the tools including pre (and it should be informed by pre's use case).

That was indeed my original idea too: To propose an RFC with adding such syntax to Rust itself, but I thought, I'd be useful to gain experience whether something like that is actually helpful first. So that's what I decided to write my thesis about.

**Comment by valpackett** [comment]
Yeah, of course

**Comment by aticu** [comment]
I just came across the [`zerocopy::AsBytes` trait](https://docs.rs/zerocopy/0.3.0/zerocopy/trait.AsBytes.html). I'm pretty sure this is the better version of `NoPaddingBytes` that I originally envisioned. Maybe that should be used instead of this quick and dirty hack.
